project:
  name: czy_all

mybatis:
  typeAliases:
    packageName: com.czy.frame..*model..*dao.*

datasource:
  mysql-czy-test:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.230.187:3306/czy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrievalx=true
    username: root
    password: chen
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1


redis:
  host: 106.54.230.187
  port: 6379
  password: chenzy
  database: 0 #Redis数据库索引（默认为0）
  lettuce:
    pool:
      max-idle: 300 #连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      max-active: 600 #连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000ms #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException；
      time-between-eviction-runs:
  timeout: 1000ms #超时时间
