project:
  name: zk_bathhouse_api
  specialSchoolPayApps:
    - schoolId: 10093
      appId: 1
    - schoolId: 25057
      appId: 15
    - schoolId: 25092
      appId: 15

mybatis:
  typeAliases:
    packageName: cn.lexiaotongvip.www..*model..*dao.*
datasource:
  mysql-czy-test:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.54.230.187:3306/czy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT&allowPublicKeyRetrievalx=true&allowMultiQueries=true
    username: root
    password: chen
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1
  pgsql_orderdata:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test.lexiaotong.online:9999/orderdatarmananger
    username: postgres
    password: postgres
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1
  pgsql_isvorderdata:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test.lexiaotong.online:9999/zfbisv
    username: postgres
    password: postgres
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1
  pgsql_channel:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test.lexiaotong.online:9999/channelmanager
    username: postgres
    password: postgres
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1
  pgsql_device:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test.lexiaotong.online:9999/devicemanage
    username: postgres
    password: postgres
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: false
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    remove-abandoned: true
    log-abandoned: true
    validation-query: select 1

redis:
  host: test.lexiaotong.online
  port: 7786
  password: 123456
  database: 0 #Redis数据库索引（默认为0）
  lettuce:
    pool:
      max-idle: 300 #连接池中的最大空闲连接
      min-idle: 0     # 连接池中的最小空闲连接
      max-active: 600 #连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000ms #最大的等待时间，如果超过等待时间，则直接抛出JedisConnectionException；
      time-between-eviction-runs:
  timeout: 1000ms #超时时间

memcache:
  servers: test.lexiaotong.cn:35600 #设置服务器地址  该端口号默认为11211，测试：test.lexiaotong.cn:35600  正式：machinemanager.lxt6.cn:35600  龙骊 120.76.65.194:35600
  poolName: memcachedPool
  failover: true #设置容错开关设置为TRUE，当当前socket不可用时，程序会自动查找可用连接并返回，否则返回NULL，默认状态是true，建议保持默认
  initConn: 20 #设置初始连接数
  minConn: 10 #设置最小连接数
  maxConn: 200 #设置最大连接数
  maintSleep: 3000   #设置连接池维护线程的睡眠时间
  nagel: false #设置是否使用Nagle算法（Socket的参数），如果是true在写数据时不缓冲，立即发送出去
  socketTO: 3000 #设置socket的读取等待超时时间
  aliveCheck: true #设置连接心跳监测开关 设为true则每次通信都要进行连接是否有效的监测，造成通信次数倍增，加大网络负载，因此该参数应该在对HA要求比较高的场合设为TRUE，默认状态是false。